package com.wugui.datax.admin.datamapper;

import com.wugui.datax.admin.dataobject.CloudAccountDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface CloudAccountDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    int insert(CloudAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    int insertSelective(CloudAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    CloudAccountDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    int updateByPrimaryKeySelective(CloudAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_account
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    int updateByPrimaryKey(CloudAccountDO record);

    /**
     * 获取云账号列表
     * @return
     */
    List<CloudAccountDO> listCloud();

    /**
     * 获取云账号列表分页
     * @param offset
     * @param pagesize
     * @param name
     * @return
     */
    List<CloudAccountDO> pageList(@Param("offset") int offset,
                           @Param("pagesize") int pagesize,
                           @Param("name") String name);

    /**
     * 获取云账号分页总数
     * @param offset
     * @param pagesize
     * @param name
     * @return
     */
    int pageListCount(@Param("offset") int offset,
                      @Param("pagesize") int pagesize,
                      @Param("name") String name);

}