package com.wugui.datax.admin.datamapper;

import com.wugui.datax.admin.dataobject.ContainerDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ContainerDOMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_task
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_task
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    int insert(ContainerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_task
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    int insertSelective(ContainerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_task
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    ContainerDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_task
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    int updateByPrimaryKeySelective(ContainerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_task
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    int updateByPrimaryKey(ContainerDO record);

    /**
     * 获取对象存储列表
     * @return
     */
    List<ContainerDO> listContainer();

    /**
     * 获取对象存储任务列表分页
     * @param offset
     * @param pagesize
     * @param name
     * @return
     */
    List<ContainerDO> pageList(@Param("offset") int offset,
                               @Param("pagesize") int pagesize,
                               @Param("name") String name);

    /**
     * 获取对象存储任务分页总数
     * @param offset
     * @param pagesize
     * @param name
     * @return
     */
    int pageListCount(@Param("offset") int offset,
                      @Param("pagesize") int pagesize,
                      @Param("name") String name);



}
