package com.wugui.datax.admin.datamapper;


import com.wugui.datax.admin.dataobject.SourceServerDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SourceServerDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_server
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_server
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    int insert(SourceServerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_server
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    int insertSelective(SourceServerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_server
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    SourceServerDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_server
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    int updateByPrimaryKeySelective(SourceServerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_server
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    int updateByPrimaryKey(SourceServerDO record);

    /**
     * 查询源服务器列表
     * @return
     */
    List<SourceServerDO> listSource();

    /**
     * 获取源服务器列表分页
     * @param offset
     * @param pagesize
     * @param name
     * @return
     */
    List<SourceServerDO> pageList(@Param("offset") int offset,
                                  @Param("pagesize") int pagesize,
                                  @Param("name") String name);

    /**
     * 获取源服务器分页总数
     * @param offset
     * @param pagesize
     * @param name
     * @return
     */
    int pageListCount(@Param("offset") int offset,
                      @Param("pagesize") int pagesize,
                      @Param("name") String name);
}