package com.wugui.datax.admin.datamapper;


import com.wugui.datax.admin.dataobject.SystemTaskDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SystemTaskDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_task
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_task
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    int insert(SystemTaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_task
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    int insertSelective(SystemTaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_task
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    SystemTaskDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_task
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    int updateByPrimaryKeySelective(SystemTaskDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_task
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    int updateByPrimaryKey(SystemTaskDO record);

    /**
     * 获取系统盘任务列表分页
     * @param offset
     * @param pagesize
     * @param name
     * @return
     */
    List<SystemTaskDO> pageList(@Param("offset") int offset,
                                  @Param("pagesize") int pagesize,
                                  @Param("name") String name);

    /**
     * 获取系统盘任务分页总数
     * @param offset
     * @param pagesize
     * @param name
     * @return
     */
    int pageListCount(@Param("offset") int offset,
                      @Param("pagesize") int pagesize,
                      @Param("name") String name);

    /**
     * 根据cloudAccountId删除任务
     * @param id
     * @return
     */
    int deleteByCloudId(Integer id);

    /**
     * 根据sourceServerId删除任务
     * @param id
     * @return
     */
    int deleteBySourceId(Integer id);

}