package com.wugui.datax.admin.dataobject;

import java.util.Date;

public class CloudAccountDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_account.id
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_account.name
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_account.type
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_account.accesskey_Id
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    private String accesskeyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_account.accesskey_secret
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    private String accesskeySecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_account.remarks
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_account.create_date
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_account.update_date
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_account.status
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_account.id
     *
     * @return the value of cloud_account.id
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_account.id
     *
     * @param id the value for cloud_account.id
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_account.name
     *
     * @return the value of cloud_account.name
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_account.name
     *
     * @param name the value for cloud_account.name
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_account.type
     *
     * @return the value of cloud_account.type
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_account.type
     *
     * @param type the value for cloud_account.type
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_account.accesskey_Id
     *
     * @return the value of cloud_account.accesskey_Id
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public String getAccesskeyId() {
        return accesskeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_account.accesskey_Id
     *
     * @param accesskeyId the value for cloud_account.accesskey_Id
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public void setAccesskeyId(String accesskeyId) {
        this.accesskeyId = accesskeyId == null ? null : accesskeyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_account.accesskey_secret
     *
     * @return the value of cloud_account.accesskey_secret
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public String getAccesskeySecret() {
        return accesskeySecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_account.accesskey_secret
     *
     * @param accesskeySecret the value for cloud_account.accesskey_secret
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public void setAccesskeySecret(String accesskeySecret) {
        this.accesskeySecret = accesskeySecret == null ? null : accesskeySecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_account.remarks
     *
     * @return the value of cloud_account.remarks
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_account.remarks
     *
     * @param remarks the value for cloud_account.remarks
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_account.create_date
     *
     * @return the value of cloud_account.create_date
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_account.create_date
     *
     * @param createDate the value for cloud_account.create_date
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_account.update_date
     *
     * @return the value of cloud_account.update_date
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_account.update_date
     *
     * @param updateDate the value for cloud_account.update_date
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_account.status
     *
     * @return the value of cloud_account.status
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_account.status
     *
     * @param status the value for cloud_account.status
     *
     * @mbg.generated Thu Jul 09 15:01:27 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}