package com.wugui.datax.admin.dataobject;

import java.util.Date;

public class SourceServerDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_server.id
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_server.name
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_server.type
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_server.ip
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_server.port
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    private String port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_server.username
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_server.password
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_server.create_date
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_server.update_date
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_server.status
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_server.id
     *
     * @return the value of source_server.id
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_server.id
     *
     * @param id the value for source_server.id
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_server.name
     *
     * @return the value of source_server.name
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_server.name
     *
     * @param name the value for source_server.name
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_server.type
     *
     * @return the value of source_server.type
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_server.type
     *
     * @param type the value for source_server.type
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_server.ip
     *
     * @return the value of source_server.ip
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_server.ip
     *
     * @param ip the value for source_server.ip
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_server.port
     *
     * @return the value of source_server.port
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_server.port
     *
     * @param port the value for source_server.port
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_server.username
     *
     * @return the value of source_server.username
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_server.username
     *
     * @param username the value for source_server.username
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_server.password
     *
     * @return the value of source_server.password
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_server.password
     *
     * @param password the value for source_server.password
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_server.create_date
     *
     * @return the value of source_server.create_date
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_server.create_date
     *
     * @param createDate the value for source_server.create_date
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_server.update_date
     *
     * @return the value of source_server.update_date
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_server.update_date
     *
     * @param updateDate the value for source_server.update_date
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_server.status
     *
     * @return the value of source_server.status
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_server.status
     *
     * @param status the value for source_server.status
     *
     * @mbg.generated Thu Jul 09 15:07:02 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}