package com.wugui.datax.admin.dataobject;

import java.util.Date;

public class SystemTaskDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_task.id
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_task.name
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_task.source_server_id
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    private Integer sourceServerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_task.cloud_account_id
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    private Integer cloudAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_task.cloud_server_ip
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    private String cloudServerIp;

    private String cloudExampleName;

    public String getCloudExampleName() {
        return cloudExampleName;
    }

    public void setCloudExampleName(String cloudExampleName) {
        this.cloudExampleName = cloudExampleName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_task.target_area
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    private String targetArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_task.broadband
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    private Integer broadband;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_task.start_type
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    private Integer startType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_task.start_time
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_task.create_time
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_task.update_time
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_task.status
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_task.spend_time
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    private Integer spendTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_task.id
     *
     * @return the value of system_task.id
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_task.id
     *
     * @param id the value for system_task.id
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_task.name
     *
     * @return the value of system_task.name
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_task.name
     *
     * @param name the value for system_task.name
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_task.source_server_id
     *
     * @return the value of system_task.source_server_id
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public Integer getSourceServerId() {
        return sourceServerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_task.source_server_id
     *
     * @param sourceServerId the value for system_task.source_server_id
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public void setSourceServerId(Integer sourceServerId) {
        this.sourceServerId = sourceServerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_task.cloud_account_id
     *
     * @return the value of system_task.cloud_account_id
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public Integer getCloudAccountId() {
        return cloudAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_task.cloud_account_id
     *
     * @param cloudAccountId the value for system_task.cloud_account_id
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public void setCloudAccountId(Integer cloudAccountId) {
        this.cloudAccountId = cloudAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_task.cloud_server_ip
     *
     * @return the value of system_task.cloud_server_ip
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public String getCloudServerIp() {
        return cloudServerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_task.cloud_server_ip
     *
     * @param cloudServerIp the value for system_task.cloud_server_ip
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public void setCloudServerIp(String cloudServerIp) {
        this.cloudServerIp = cloudServerIp == null ? null : cloudServerIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_task.target_area
     *
     * @return the value of system_task.target_area
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public String getTargetArea() {
        return targetArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_task.target_area
     *
     * @param targetArea the value for system_task.target_area
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public void setTargetArea(String targetArea) {
        this.targetArea = targetArea == null ? null : targetArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_task.broadband
     *
     * @return the value of system_task.broadband
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public Integer getBroadband() {
        return broadband;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_task.broadband
     *
     * @param broadband the value for system_task.broadband
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public void setBroadband(Integer broadband) {
        this.broadband = broadband;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_task.start_type
     *
     * @return the value of system_task.start_type
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public Integer getStartType() {
        return startType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_task.start_type
     *
     * @param startType the value for system_task.start_type
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public void setStartType(Integer startType) {
        this.startType = startType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_task.start_time
     *
     * @return the value of system_task.start_time
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_task.start_time
     *
     * @param startTime the value for system_task.start_time
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_task.create_time
     *
     * @return the value of system_task.create_time
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_task.create_time
     *
     * @param createTime the value for system_task.create_time
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_task.update_time
     *
     * @return the value of system_task.update_time
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_task.update_time
     *
     * @param updateTime the value for system_task.update_time
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_task.status
     *
     * @return the value of system_task.status
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_task.status
     *
     * @param status the value for system_task.status
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_task.spend_time
     *
     * @return the value of system_task.spend_time
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public Integer getSpendTime() {
        return spendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_task.spend_time
     *
     * @param spendTime the value for system_task.spend_time
     *
     * @mbg.generated Fri Jul 10 15:40:51 CST 2020
     */
    public void setSpendTime(Integer spendTime) {
        this.spendTime = spendTime;
    }
}